# Example configuration.yaml entry
fan:
  - platform: ecovent
    ip_address: "192.168.1.200"

  - platform: ecovent
    name: Kitchen fan
    ip_address: "192.168.1.205"
    device_id: "85481285"
    port: 4000
    password: !secret blauberg_pass